runtime: nodejs18

# Cloud Run configuration
env_variables:
  PORT: 8080
  NODE_ENV: production

# Resource limits
# Optimized for real-time multiplayer gaming
automatic_scaling:
  min_instances: 1  # Keep 1 instance always warm to avoid cold starts
  max_instances: 5  # Lower max to reduce container churn and connection drops
  target_cpu_utilization: 0.75  # Higher threshold for more stable performance

resources:
  cpu: 2  # Increased from 1 for better game loop performance
  memory_gb: 2  # Increased from 0.5 to reduce GC pauses

# Health check
liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1
