runtime: nodejs18

# Cloud Run configuration
env_variables:
  PORT: 8080
  NODE_ENV: production

# Resource limits
automatic_scaling:
  min_instances: 0
  max_instances: 20
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5

# Health check
liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 1
