apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: preview-feature-client-side-prediction
  annotations:
    run.googleapis.com/launch-stage: BETA
  labels:
    environment: preview
    branch: feature-client-side-prediction
    commit: 4fa3bd2
spec:
  template:
    metadata:
      annotations:
        # Maximum concurrent requests per instance
        run.googleapis.com/execution-environment: gen2
        # CPU is always allocated (no throttling)
        run.googleapis.com/cpu-throttling: "false"
    spec:
      # Keep container always allocated (reduces cold starts)
      containerConcurrency: 1000
      timeoutSeconds: 3600  # 1 hour timeout for WebSockets
      containers:
      - image: gcr.io/raga-io-476815/preview-feature-client-side-prediction
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "512Mi"
        env:
        # PORT is automatically set by Cloud Run
        - name: NODE_ENV
          value: "production"
        - name: PRIVY_APP_ID
          value: "cmhkpg56r02vbjr0cdeex8n7i"
        - name: DATABASE_URL
          value: "postgresql://neondb_owner:npg_X0hNZFwe8Lrk@ep-wild-bar-agks6pgk-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require"
        - name: DEPLOYMENT_TYPE
          value: "preview"
        - name: GIT_BRANCH
          value: "feature/client-side-prediction"
        - name: GIT_COMMIT
          value: "4fa3bd2"
  traffic:
  - percent: 100
    latestRevision: true
